### PR TITLE
Fix #2

### LINKED ISSUE #2: Raises File not open for writing (IO::Error)
some backward incompatibility of crystal. used to work.

### PR DESCRIPTION
**Pull request by bew**

### CODE REVIEW

**Comment by bew** [comment]
You need to merge #4 in order to compile..

**Comment by repomaa** [comment]
Does the code work without the reopenings?

**Comment by bew** [comment]
No, I had the `File not open for writing (IO::Error)` error.. 

In fact I don't really understand why you did the reopening thing, so I deleted it and it worked..

**Comment by bew** [comment]
Are you ever gonna merge/review this? otherwise let's close it

**Comment by repomaa** [comment]
I'm sorry. This dropped below my radar. Merged!

**Pull request merged**
